# Generated by Django 4.2.3 on 2023-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0002_product_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_image',
            field=models.ImageField(null=True, upload_to='transaction'),
        ),
    ]
