# Generated by Django 4.2.3 on 2023-07-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0003_purchase_transaction_id_purchase_transaction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('user_purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adnoc_app.purchase')),
            ],
        ),
    ]
