# Generated by Django 4.2.3 on 2023-07-29 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0004_purchase_transaction_id_purchase_transaction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earning', models.FloatField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
