# Generated by Django 4.2.3 on 2023-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0011_adnocuser_withdrawable_amount_withdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='withdrawable_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
