# Generated by Django 4.2.3 on 2023-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0012_alter_adnocuser_withdrawable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='staus',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
