# Generated by Django 4.2.3 on 2023-07-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0013_withdrawrequest_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawrequest',
            old_name='staus',
            new_name='status',
        ),
    ]
