# Generated by Django 4.2.3 on 2023-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0015_alter_adnocuser_options_alter_adnocuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
