# Generated by Django 4.2.3 on 2023-08-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0017_adnocuser_recharge_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_date', models.DateTimeField(null=True)),
                ('transaction_id', models.CharField(max_length=30, null=True)),
                ('transaction_image', models.ImageField(null=True, upload_to='transaction')),
                ('is_valid', models.BooleanField(default=False, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
