# Generated by Django 4.2.3 on 2023-08-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0018_recharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recharge',
            new_name='UserRecharge',
        ),
    ]
