# Generated by Django 4.2.3 on 2023-08-01 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0021_alter_userrecharge_user_id_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accname', models.TextField()),
                ('accnum', models.TextField()),
                ('ifsc', models.TextField()),
                ('mobnum', models.IntegerField()),
                ('acctype', models.TextField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
