# Generated by Django 4.2.3 on 2023-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0022_userbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='trans_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
