# Generated by Django 4.2.3 on 2023-08-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0005_adnocuser_withdrawable_amount_withdrawrequest'),
        ('adnoc_app', '0023_alter_transactions_trans_date'),
    ]

    operations = [
    ]
