# Generated by Django 4.2.3 on 2023-08-03 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0026_alter_adnocuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('299dfe39-e407-4e79-b698-ab5d7d2cfc5d')),
        ),
    ]
