# Generated by Django 4.2.3 on 2023-08-03 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0028_alter_adnocuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('50782faa-e9b9-49c5-9c08-eca6503fbfc5')),
        ),
    ]
