# Generated by Django 4.2.3 on 2023-08-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0030_alter_adnocuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('1718ff30-a1df-4df5-b2e4-077f0ee66b45')),
        ),
        migrations.AlterField(
            model_name='adnocuser',
            name='refered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
