# Generated by Django 4.2.3 on 2023-08-03 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0031_alter_adnocuser_referal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('ee95e96f-35a2-4dbd-8271-d5e37405d9ee')),
        ),
    ]
