# Generated by Django 4.2.3 on 2023-08-03 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0032_alter_adnocuser_referal_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adnocuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('70c7ff00-e962-4674-b934-8788780dfc62')),
        ),
    ]
