# Generated by Django 4.2.3 on 2023-08-03 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0033_alter_adnocuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('542f852c-c2c2-4bc2-9b15-01cf76db4d13')),
        ),
    ]
