# Generated by Django 4.2.3 on 2023-08-03 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0034_alter_adnocuser_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('8aec1a00-387f-4b78-956e-514a10da217a')),
        ),
    ]
