# Generated by Django 4.2.3 on 2023-08-03 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0035_alter_adnocuser_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('c4319b04-2ed4-4a9b-863c-084bc964df2e')),
        ),
        migrations.AlterField(
            model_name='adnocuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
