# Generated by Django 4.2.3 on 2023-08-04 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0036_alter_adnocuser_referal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='referal_code',
            field=models.TextField(default=uuid.UUID('32e25d3f-6207-4543-b801-2ba1b6b0a5bb')),
        ),
    ]
