# Generated by Django 4.2.3 on 2023-08-08 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0039_alter_adnocuser_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnocuser',
            name='refered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
