# Generated by Django 4.2.3 on 2023-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adnoc_app', '0041_upiaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
